/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFlightsRouteImport } from './routes/api/flights'
import { Route as ApiRouteIcao24RouteImport } from './routes/api/route/$icao24'
import { Route as ApiFlightIcao24RouteImport } from './routes/api/flight/$icao24'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlightsRoute = ApiFlightsRouteImport.update({
  id: '/api/flights',
  path: '/api/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteIcao24Route = ApiRouteIcao24RouteImport.update({
  id: '/api/route/$icao24',
  path: '/api/route/$icao24',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlightIcao24Route = ApiFlightIcao24RouteImport.update({
  id: '/api/flight/$icao24',
  path: '/api/flight/$icao24',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/flight/$icao24': typeof ApiFlightIcao24Route
  '/api/route/$icao24': typeof ApiRouteIcao24Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/flight/$icao24': typeof ApiFlightIcao24Route
  '/api/route/$icao24': typeof ApiRouteIcao24Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/flight/$icao24': typeof ApiFlightIcao24Route
  '/api/route/$icao24': typeof ApiRouteIcao24Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/sitemap.xml'
    | '/api/flights'
    | '/api/flight/$icao24'
    | '/api/route/$icao24'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/sitemap.xml'
    | '/api/flights'
    | '/api/flight/$icao24'
    | '/api/route/$icao24'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/sitemap.xml'
    | '/api/flights'
    | '/api/flight/$icao24'
    | '/api/route/$icao24'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiFlightsRoute: typeof ApiFlightsRoute
  ApiFlightIcao24Route: typeof ApiFlightIcao24Route
  ApiRouteIcao24Route: typeof ApiRouteIcao24Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flights': {
      id: '/api/flights'
      path: '/api/flights'
      fullPath: '/api/flights'
      preLoaderRoute: typeof ApiFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/route/$icao24': {
      id: '/api/route/$icao24'
      path: '/api/route/$icao24'
      fullPath: '/api/route/$icao24'
      preLoaderRoute: typeof ApiRouteIcao24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flight/$icao24': {
      id: '/api/flight/$icao24'
      path: '/api/flight/$icao24'
      fullPath: '/api/flight/$icao24'
      preLoaderRoute: typeof ApiFlightIcao24RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiFlightsRoute: ApiFlightsRoute,
  ApiFlightIcao24Route: ApiFlightIcao24Route,
  ApiRouteIcao24Route: ApiRouteIcao24Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
